/*
 * Copyright (C) 2017 hteran.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package vista;

import basededatos.BaseDatosOracle;
import java.util.ArrayList;
import model.geografia.Pais;
import modelo.SuperTabla;

/**
 *
 * @author hteran
 */
public class FormPais extends FormTemplate {

    /**
     * Creates new form FormMunicipio
     */
    public FormPais() {
        initComponents();
        inicializar();
        mostrarRegistro(0);
        textCodigo.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textCodigo = new javax.swing.JFormattedTextField();
        textNombre = new javax.swing.JTextField();
        textIso2 = new javax.swing.JTextField();
        textIso3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textIso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIso3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Iso 3");

        jLabel3.setText("Iso 2");

        jLabel2.setText("Nombre");

        jLabel1.setText("Código");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(textIso2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(textIso3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(textCodigo))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(366, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textIso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIso3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIso3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JFormattedTextField textCodigo;
    private javax.swing.JTextField textIso2;
    private javax.swing.JTextField textIso3;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
    @Override
    public void limpiarFormulario() {
        textCodigo.setValue(null);
        textNombre.setText(null);
        textIso2.setText(null);
        textIso3.setText(null);
        textNombre.requestFocus();
    }

    @Override
    public void mostrarRegistro(int indice) {
        textCodigo.requestFocus();
        if (indice < 0 || listaDatos.isEmpty()) {
            limpiarFormulario();
            return;
        }
        Pais pais;
        pais = (Pais) listaDatos.get(indice);
        if (pais != null) {
            System.out.println(pais);
            textCodigo.setValue(pais.getCodigo());
            textNombre.setText(pais.getNombre());
            textIso2.setText(pais.getIso2());
            textIso3.setText(pais.getIso3());
            textNombre.requestFocus();
        }
    }

    @Override
    public void inicializar() {
        try {
            listaDatos = new ArrayList<>();
            listaDatos.addAll(Pais.buscar());
            indiceActual = 0;
            habilitarNavegacion();
        } catch (Exception ex) {
            mostrarException(ex);
        }
    }

    @Override
    public SuperTabla getNuevoRegistro() throws Exception {
        Pais pais;
        pais = new Pais(textNombre.getText(), textIso2.getText(),
                textIso3.getText());
        return pais;
    }

    @Override
    public void setRegistroActual(SuperTabla registro) throws Exception {
        Pais pais;
        pais = (Pais) registro;
        pais.setNombre(textNombre.getText());
        pais.setIso2(textIso2.getText());
        pais.setIso3(textIso3.getText());
    }

    @Override
    public void ejecutarBusqueda() throws Exception {
        long codigo = 0;
        codigo = textCodigo.getText().isEmpty()
                ? -1
                : Long.parseLong(textCodigo.getText());
        indiceActual = 0;
        listaDatos = new ArrayList<>();
        if (codigo == -1) {
            listaDatos.addAll(Pais.buscar());
        } else {
            listaDatos.add(Pais.buscar(codigo));
        }
        textCodigo.setEditable(false);
    }

    @Override
    public void habilitarBusqueda() {
        textCodigo.setEditable(true);
        textCodigo.requestFocus();
    }

    @Override
    public void imprimirJasper() {
        try {
            listaDatos.get(indiceActual)
                    .abrirReporte(BaseDatosOracle.getInstance().getConexion());

        } catch (Exception ex) {
            mostrarException(ex);
        }

    }

}
