package modelo.lectura;
// Generated May 12, 2017 7:15:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import modelo.atencion.Casas;

/**
 * Medidores generated by hbm2java
 */
public class Medidores {


     private BigDecimal id;
     private Casas casas;
     private String serial;
     private BigDecimal costo;

    public Medidores() {
    }

	
    public Medidores(BigDecimal id, Casas casas, String serial, BigDecimal costo) {
        this.id = id;
        this.casas = casas;
        this.serial = serial;
        this.costo = costo;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Casas getCasas() {
        return this.casas;
    }
    
    public void setCasas(Casas casas) {
        this.casas = casas;
    }
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }




}


