package modelo.lectura;
// Generated May 12, 2017 7:15:35 PM by Hibernate Tools 4.3.1


import basededatos.BaseDatosOracle;
import static basededatos.Secuencia.nextVal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import modelo.atencion.Casa;

/**
 * Medidores generated by hbm2java
 */
public class Medidor {


     private long id;
     private Casa casas;
     private String serial;
     private long costo;

    public Medidor() {
    }

	
    public Medidor(long id, Casa casas, String serial, long costo) {
        this.id = id;
        this.casas = casas;
        this.serial = serial;
        this.costo = costo;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Casa getCasas() {
        return this.casas;
    }
    
    public void setCasas(Casa casas) {
        this.casas = casas;
    }
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }
    public long getCosto() {
        return this.costo;
    }
    
    public void setCosto(long costo) {
        this.costo = costo;
    }

    public int insertar() throws SQLException{
        long secuencia = nextVal("SECTORES_SEQ");
         BaseDatosOracle basededatos = BaseDatosOracle.getInstance();
        String sql = "INSERT INTO MEDIDORES (ID,SERIAL,COSTO,CASA_ID) "
                + "VALUES(?,?,?,?)";
        int ejecucion;
        basededatos.conectar();
        basededatos.prepararSql(sql);
        basededatos.asignarParametro(1, secuencia);
        basededatos.asignarParametro(2, getSerial());
        basededatos.asignarParametro(3, getCosto());
        basededatos.asignarParametro(4, getCasas().getId());
        ejecucion = basededatos.ejecutar();
        basededatos.cerrarSentencia();
        return ejecucion;
    }
    
    public int actualizar() throws SQLException{
       BaseDatosOracle basededatos = BaseDatosOracle.getInstance();
        String sql;
        int ejecucion;
        sql = "UPDATE MEDIDORES SET SERIAL = ?,COSTO = ?,CASA_ID = ? WHERE ID = ?";
        basededatos.conectar();
        basededatos.prepararSql(sql);
        basededatos.asignarParametro(1, getSerial());
        basededatos.asignarParametro(2, getCosto());
        basededatos.asignarParametro(3, getCasas().getId());
        basededatos.asignarParametro(4, getId());
        ejecucion = basededatos.ejecutar();
        basededatos.cerrarSentencia();
        return ejecucion;
    }
    
    public int eliminar() throws SQLException{
        BaseDatosOracle basededatos;
        basededatos = BaseDatosOracle.getInstance();
        String sql;
        int ejecucion;
        sql = "DELETE MEDIDORES SECTORES WHERE ID = ?";
        basededatos.conectar();
        basededatos.prepararSql(sql);
        basededatos.asignarParametro(1, getId());
        ejecucion = basededatos.ejecutar();
        basededatos.cerrarSentencia();
        return ejecucion;
    }
    
    /*public ArrayList<Sector> listar() throws SQLException {
        ArrayList<Medidor> datos = new ArrayList<>();
        BaseDatosOracle bd = BaseDatosOracle.getInstance();
        String sql = "SELECT ID, SERIAL, COSTO, CASA_ID FROM MEDIDORES";
        bd.conectar();
        bd.prepararSql(sql);
        ResultSet cursor = bd.ejecutarQuery();
        datos.clear();
        while (cursor.next()) {
            datos.add(
                    new Sector(
                            cursor.getBigDecimal("ID"), 
                            cursor.getString("DET")
                    )
            );
        }
        return datos;
    }*/
}

