package modelo.lectura;
// Generated May 12, 2017 7:15:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Periodos generated by hbm2java
 */
public class Periodos {


     private BigDecimal id;
     private BigDecimal periodo;
     private BigDecimal lectura;
     private BigDecimal facturado;

    public Periodos() {
    }

	
    public Periodos(BigDecimal id, BigDecimal periodo, BigDecimal lectura, BigDecimal facturado) {
        this.id = id;
        this.periodo = periodo;
        this.lectura = lectura;
        this.facturado = facturado;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public BigDecimal getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(BigDecimal periodo) {
        this.periodo = periodo;
    }
    public BigDecimal getLectura() {
        return this.lectura;
    }
    
    public void setLectura(BigDecimal lectura) {
        this.lectura = lectura;
    }
    public BigDecimal getFacturado() {
        return this.facturado;
    }
    
    public void setFacturado(BigDecimal facturado) {
        this.facturado = facturado;
    }
}


