package modelo.lectura;
// Generated May 12, 2017 7:15:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Sectores generated by hbm2java
 */
public class Sectores {

    private BigDecimal id;
    private String det;

    public Sectores() {
    }

    public Sectores(BigDecimal id, String det) {
        this.id = id;
        this.det = det;
    }

    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    public String getDet() {
        return this.det;
    }

    public void setDet(String det) {
        this.det = det;
    }
}
